python -u scripts/image_sample.py \
  --batch_size 32 \
  --training_mode consistency_training \
  --sampler onestep \
  --model_path CKPT_DIR/ict_imagenet64_no32_qkv_4096/ema_0.99997_680000.pt \
  --save_dir samples \
  --exp_name ict_imagenet64_no32_qkv_4096 \
  --attention_resolutions 16,8 \
  --class_cond True \
  --use_scale_shift_norm False \
  --dropout 0.0 \
  --image_size 64 \
  --num_channels 192 \
  --num_head_channels 64 \
  --num_res_blocks 3 \
  --num_samples 50000 \
  --resblock_updown True \
  --use_fp16 True \
  --weight_schedule uniform